hostname: rancher
rancher:
  console: default
  docker:
    data-root: /mnt/storage/docker
    engine: docker-19.03.11
    graph: /mnt/storage/docker
    storage_driver: zfs
  network:
    interfaces:
      eth1:
        address: 192.168.178.35/24
        dhcp: false
        gateway: 192.168.178.1
        mtu: 1500
  services_include:
    /var/lib/rancher/conf/couchpotato.yml: false
    /var/lib/rancher/conf/letsencrypt.yml: true
    /var/lib/rancher/conf/lidarr.yml: true
    /var/lib/rancher/conf/oauth.yml: true
    /var/lib/rancher/conf/plex.yml: true
    /var/lib/rancher/conf/portainer.yml: true
    /var/lib/rancher/conf/sabnzbd.yml: true
    /var/lib/rancher/conf/sonarr.yml: false
    /var/lib/rancher/conf/sonarr3.yml: true
    /var/lib/rancher/conf/unifi.yml: false
    /var/lib/rancher/conf/wordpress.yml: false
    /var/lib/rancher/conf/radarr.yml: true
    crontab: true
    https://raw.githubusercontent.com/prupp/rancheros/master/radarr.yml: true
    kernel-headers-system-docker: true
    zfs: true
write_files:
- content: |+
    30 05 * * * /home/rancher/backup_to_synology.sh
    00 04 * * 1 /home/rancher/updates/update_all_container.sh
  group: root
  owner: root
  path: /var/spool/cron/crontabs/root
  permissions: "0600"
- content: |+
    #!/bin/bash
    crond
  owner: root
  path: /etc/rc.local
  permissions: "0755"